apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-vantage-viz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpha-vantage-viz-app
  template:
    metadata:
      labels:
        app: alpha-vantage-viz-app
    spec:
      containers:
      - name: alpha-vantage-viz-app
        image: your-image-name
        ports:
        - containerPort: 5000
        env:
        - name: ENVIRONMENT
          value: "AKS_PRD"
        volumeMounts:
        - name: secret-volume
          mountPath: "/app/secrets"
      volumes:
      - name: secret-volume
        secret:
          secretName: azure-secret
